### ISSUE TITLE
GPIO pin stopped

### ISSUE THREAD

**Issue by Jamos1988** [SignalK/signalk-node-red#6]
Hi,

I realize this maybe has something more to do with the node I am using, rather then the signalk-node-red, but I am looking for some advice. Hope you can support.

Somehow, after I installed the new Node-red webapp within SignalK, my GPIO pins have stopped working.
They are in the stopped state, as described in this forum: https://discourse.nodered.org/t/nrpgio-python-command-not-running/15943/5

I am using the node https://flows.nodered.org/node/node-red-node-pi-gpio

Any idea what might have caused this and how I can troubleshoot? I tried the solutions from the forum to no avail.

**Comment by tkurki** [comment]
If I were you I would
- disable the sk plugin
- install a standalone, older version Node-RED
- install older version of the gpio plugin

Consult node-RED documentation, `npm install foobar@version` is how you install a specific version.

**Comment by Jamos1988** [comment]
It was solved by adjusting the underlying python script, and choosing BCM mode rather than GPIO mode. This is needed for when using compute module.
